### ISSUE TITLE
How to bring back Native execution on my chain?

### ISSUE THREAD

**Issue by tdelabro** [paritytech/polkadot-sdk#2891]
Hey,

I know native execution has been removed in a recent update. We can only execute in Wasm, which has a clear impact on my chain TPS.

I want to be able to execute in Native again. How can I have it back?

I think it is still there, somewhere in the codebase, because pallet's tests are still run in Native. So, is it as simple as tweaking a config or changing a bool somewhere, or will it require me to fork Substrate? If I have to fork, could you point me to where is the code I have to change?

Also, I would like to know the exact PR that removed Native execution. It will probably be helpful in my endeavors.

Best regards

**Comment by ggwpez** [comment]
The problem is that native is not guaranteed to be deterministic like WASM. I think there were a few MRs about this from @michalkucharczyk.

What kind of performance degradation do you see? Did you compile with `lto` and `codegen-units = 1` to get the most perf?

**Comment by bkchr** [comment]
> I know native execution has been removed in a recent update. We can only execute in Wasm, which has a clear impact on my chain TPS.

Yeah, please provide some numbers. For sure wasm is slower, but it should be not that much slower.

**Comment by tdelabro** [comment]
Here is a portion of my `Cargo.toml`
```toml
[profile.production]
inherits = "release"
codegen-units = 1    # Setting this to 1 allows for more optimizations at the cost of slower compile time
lto = true           # Enables Link Time Optimization, enabling more aggressive optimizations across the entire codebase
opt-level = 3        # Optimize for speed regardless of binary size or compile time
rpath = false        # Disables adding rpath to the binary
```

`lto` is enable, `codegen-units` too.

We are around 40 TPS in Native and if we revert back to `git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.43"` we are at 70TPS.

We use Substrate to run a VM whose execution is provable and deterministic. So we already have this guarantee.
And the Substrate run is just for sequencing, we do another run asynchronously that is provable. 
So, for the Substrate run we really just aim for raw performances.
