### ISSUE TITLE
Error: Input("Error mmaping spec file `polkadot`: No such device (os error 19)")

### ISSUE THREAD

**Issue by klestrong** [paritytech/polkadot-sdk#4303]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

I've been running previous versions of Polkadot v1.10.0 and older successfully, but cannot get Polkadot Parchain v1.10.1 to run. The docker-compose execution is below with the resulting error message, "Error mmaping spec file `polkadot`".  Also below is my docker-compose file.  I've updated my docker-compose to latest and commented out some arguements with no success.  I've checked this Github repo for that error and parts of the error.  I did the same on https://substrate.stackexchange.com as suggested with no resolution.
`Error:`
```
ubuntu@polkadot-collector:~/polkadot-parachain-v1.10.1$ cd ~/polkadot-parachain-v1.10.1 ; docker compose -f docker-compose.yml up -d && docker logs -f $(docker ps | grep polkadot | awk -F " " '{print $1}')
[+] Running 1/1
 ✔ Container PolkadotSteelBlue  Started
 2.5s  Error: Input("Error mmaping spec file `polkadot`: No such device (os error 19)")
```
`docker-compose.yml:`
```
version: '3.7'

services:
  polkadot:
    container_name: my-polkadot-container-name
    image: parity/polkadot-parachain:1.10.1
    ports:
      - 30333:30333 # p2p port
      - 9933:9933 # rpc port
      - 9944:9944 # ws port
    volumes:
      - /mnt/polkadot-pv:/parity
    command:
      - --name=my-node-name
      - --chain=polkadot
      - --database=paritydb
      - --rpc-port=9944
      - --port=30333
      - --rpc-external
      - --rpc-cors=all
      - --in-peers=100
      - --out-peers=100
      - --wasm-execution=Compiled
```
