### ISSUE TITLE
Export substrate-test-runtime crates through Umbrella

### ISSUE THREAD

**Issue by SailorSnoW** [paritytech/polkadot-sdk#5937]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Motivation

As we want to migrate the Frontier repo to use the polkadot-sdk umbrella, Frontier dependencies rely on using the `substrate-test-runtime-client` crate which isn't included in the umbrella crate and we end up having an extra external dependency as the end, which is kinda frustrating as we can't fully rely on the umbrella crate:

```toml
polkadot-sdk = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2407" }
# Waiting integration to umbrella
substrate-test-runtime-client = { git = "https://github.com/paritytech/polkadot-sdk", branch = "stable2407" }
```

### Request

Integrate `the substrate-test-runtimes` crates to the Umbrella crate.

### Are you willing to help with this request?

Yes!
