### ISSUE TITLE
Why is PvfCheckRejected event reported?

### ISSUE THREAD

**Issue by hqwangningbo** [paritytech/polkadot-sdk#6525]
https://github.com/bifrost-io/bifrost/commit/393ddc9f111244b8e0cb5a5be07750c7e683b1f0#diff-34e9fcd58b628ed526643e8c14b6563a889d664ef9c082a774c370dbea601076

We found that when this commit is included, our Runtime upgrade fails, and removing this commit makes the upgrade successful.
A long time ago, we made the changes here in Bifrost Kusama runtime, but the upgrade didn't have any problems at that time. It makes me wonder.

<img width="851" alt="image" src="https://github.com/user-attachments/assets/ecf6bf8b-ef72-4abd-9048-e4e58e5a90fe">

Zombienet: 
1. chain spec: rococo local
2. Polkadot Version: stable2409
3. Bifrost Version: release-polkadot-v1.13.0

```toml
[settings]
node_spawn_timeout = 240

[relaychain]
default_command = "/Volumes/project/bifrost-scripts/bin/polkadot-2049/polkadot"
default_args = [ "-lparachain=debug,xcm=trace" ]
chain = "rococo-local"

[[relaychain.nodes]]
name = "alice-rococo-validator"
validator = true
rpc_port = 9932
ws_port = 9942
balance = 2000000000000

[[relaychain.nodes]]
name = "bob-rococo-validator"
validator = true
rpc_port = 9933
ws_port = 9943
balance = 2000000000000

[[relaychain.nodes]]
name = "charlie-rococo-validator"
validator = true
rpc_port = 9934
ws_port = 9944
balance = 2000000000000

[[parachains]]
id = 2030
chain = "bifrost-polkadot-local"
cumulus_based = true

# run alice as parachain collator
[[parachains.collators]]
name = "bifrost-polkadot-collator1"
validator = true
command = "bifrost-v0.14.0"
rpc_port = 8933
ws_port = 8943
args = [
    "-lparachain=debug,xcm=trace"
]

# run bob as parachain collator
[[parachains.collators]]
name = "bifrost-polkadot-collator2"
validator = true
command = "bifrost-v0.14.0"
rpc_port = 8934
ws_port = 8944
args = [
    "-lparachain=trace,xcm=trace"
]
```
