### ISSUE TITLE
PoV exceeded maximum

### ISSUE THREAD

**Issue by hqwangningbo** [paritytech/polkadot-sdk#7702]
[Bifrost Mainnet wasm version](https://github.com/bifrost-io/bifrost/releases/download/bifrost-v0.16.2/bifrost-polkadot_runtime.compact.compressed.wasm)

Upgraded target wasm: [bifrost_polkadot_runtime.compact.compressed.wasm.zip](https://github.com/user-attachments/files/18953241/bifrost_polkadot_runtime.compact.compressed.wasm.zip)

I tested the upgrade using zombienet and found that I couldn't get it to work. The logs are as follows:
```txt
2025-02-24 18:38:48.093  INFO tokio-runtime-worker substrate: [Parachain🌈] 🆕 Imported #24 (0x95f6…584c → 0x43b9…62d5)
2025-02-24 18:38:48.112  INFO tokio-runtime-worker aura::cumulus: [Parachain🌈] PoV size { header: 0.3271484375kb, extrinsics: 3.939453125kb, storage_proof: 7646.2900390625kb }
2025-02-24 18:38:48.112  INFO tokio-runtime-worker aura::cumulus: [Parachain🌈] Compressed PoV size: 7650.74609375kb
2025-02-24 18:38:48.114 DEBUG tokio-runtime-worker parachain::collation-generation: [Relaychain] PoV exceeded maximum size para_id=2030 size=7834368 max_size=5242880
```
The current maxPovSize parameter for Relaychain is 5,242,880, which is consistent with Polkadot mainnet, but there is still a problem. I manually changed maxPovSize to 9,242,880 and the upgrade worked.

Does Polkadot mainnet fail to upgrade? Please help to confirm this issue, Bifrost will only upgrade to the next version when it's OK.

**Comment by hqwangningbo** [comment]
@bkchr [alice-1.log](https://github.com/user-attachments/files/18960278/alice-1.log)

**Comment by hqwangningbo** [comment]
There are some migrations, but even if delete it, it still reports the same error.

**Comment by bkchr** [comment]
@hqwangningbo why are you having constantly 2MIB+ storage proof size?

> 2025-02-25 16:35:30.060  INFO tokio-runtime-worker aura::cumulus: [Parachain🌈] Compressed PoV size: 2644.0927734375kb

**Comment by bkchr** [comment]
> Maybe there is some storage read and write in pallet hook?

Yeah maybe. I mean this is your code :) I don't know what it is doing.

**Comment by bkchr** [comment]
Do you also have this on your main net?

**Comment by bkchr** [comment]
BTW, you are running all the FRAME pallets from us with the `SubstrateWeight`. You should also benchmark them!

**Comment by hqwangningbo** [comment]
Are you using Mac?

**Comment by bkchr** [comment]
No

**Comment by hqwangningbo** [comment]
binary: https://github.com/bifrost-io/bifrost/releases/download/bifrost-v0.16.2
```toml
[relaychain]
default_command = "polkadot"
default_args = [ "-lparachain=debug" ]
chain = "rococo-local"

    [[relaychain.nodes]]
    name = "alice"
    validator = true

    [[relaychain.nodes]]
    name = "bob"
    validator = true

[[parachains]]
id = 2030
chain = "bifrost-polkadot-local"

    # run alice as parachain collator
    [[parachains.collators]]
    name = "alice"
    validator = true
    command = "bifrost-v0.16.2"
    rpc_port = 8933
    ws_port = 8943
    args = [
        "-lparachain=debug,xcm=trace"
    ]
```
Run command: 
```shell
zombienet --provider native spawn bifrost.toml
```
