### ISSUE TITLE
--telemetry-url <URL VERBOSITY> ,Verbosity is configured but not taking effect in v1.18.0

### ISSUE THREAD

**Issue by ioomie** [paritytech/polkadot-sdk#7806]
### Is there an existing issue?

- [x] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [x] This is not a support question.

### Description of bug

I updated the image version of my chain node on the Kubernetes cluster from parity/polkadot:v1.17.2 to the latest released Docker image: parity/polkadot:v1.18.0.

After I restarted it, my chain node encountered an error:

```
Starting binary polkadot  
error: invalid value 'wss://telemetry-backend.w3f.community/submit' for '--telemetry-url <URL VERBOSITY>': Verbosity level missing  

For more information, try '--help'.  
```

![Image](https://github.com/user-attachments/assets/b7f1adff-b002-470e-86cc-34a3d068a84b)

After I rolled back to version v1.17.2, it recovered and no longer showed the above error. Everything is working normally again.

Below is a part of my startup configuration:
```
...
spec:
  containers:
  - args:
    - --base-path=/chain-data
    - --rpc-cors=all
    - --port=29252
    - --unsafe-rpc-external
    - --validator
    - --rpc-methods=Unsafe
    - --name=OnfValidator
    - --chain=kusama
    - --db-cache=512
    - --telemetry-url=wss://telemetry-backend.w3f.community/submit 1
    - --in-peers=100
    - --in-peers-light=0
...
```

![Image](https://github.com/user-attachments/assets/a0e3d10d-ef85-4196-b3e9-975a746b062f)

### Steps to reproduce

All issues were reproduced in the Kubernetes environment:

1. When starting, the --telemetry-url configuration was set in version v1.18.0.2
2. After waiting for the startup, an error was reported: ERROR.
3. After rolling back to v1.17.2 with the same --telemetry-url configuration, the startup proceeded normally.
