### ISSUE TITLE
cannot find macro `thread_local` in this scope

### ISSUE THREAD

**Issue by rakeshquotus** [paritytech/polkadot-sdk#8320]
Im trying to use this pallet-evm = { version = "5.0.0", default-features = false }
pallet-contracts = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.14.0", default-features = false }

but finding some error

**Comment by clangenb** [comment]
If you compile to std, i.e. just run cargo build, you need to have the following section in your Cargo.toml:

```toml
[features]
default = ["std"]
std = [
   "pallet-contracts/std"
]
```

You can see other examples in this repository.
